version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: pytype
    versions:
    - 2020.10.8
    - 2021.2.23
    - 2021.3.10
    - 2021.3.22
    - 2021.3.3
    - 2021.4.1
    - 2021.4.15
    - 2021.4.9
  - dependency-name: marshmallow
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pyre-check
    versions:
    - 0.0.59
    - 0.0.60
    - 0.0.62
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: pydocstyle
    versions:
    - 5.1.1
