language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - pytest --cov-report=xml --cov=falcontyping tests

after_success:
  - codecov
